### ISSUE TITLE
Persistence of Fork-analysis

### ISSUE THREAD

**Issue by duckth** [duckth/bdsa-project-newgit#56]
We should store previously analysed forks in the database.
<br>
### Notes
Add a relationship to the Analysis entity: Analysis 0..N Forks
<br>
Fork(analysisId, repoIdentifier)

**Comment by duckth** [comment]
This is probably not relevant, as there would be no way to check if our database of forks is up-to-date without doing the actual API request to GitHub for the forks. And if we do that every time there's not really anything to gain by persisiting the data.

**Comment by fredpetersen** [comment]
Closing this issue for now, as it is cluttering the issues tab
