### ISSUE TITLE
Make diagram of REST API

### ISSUE THREAD

**Issue by lucasfth** [duckth/bdsa-project-newgit#79]
Illustrate the architecture of your REST service using a suitable notation. Additionally, illustrate with an UML activity diagram the sequence of operations that your GitInsight application performs once triggered with a respective GET request and until it responds with the corresponding JSON data.
-- docs/project-description.md

**Comment by lucasfth** [comment]
I am not sure if this issue is completed. As you have made the Plant UML code. But I am not sure if the code is fully done. 
The png has been put into the project as well.

**Comment by fredpetersen** [comment]
Closed by #72
